version: '3.7'

services:
  mongodb:
    image: mongo:7.0.2
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
  alan-oss:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/app/src
      - ./dist:/usr/app/dist
      - ./resources:/usr/app/resources
    container_name: alan-oss
    command: pnpm run start:dev